export enum ProductQueryAction{
    GET_ALL_PRODUCTS="GET_ALL_PRODUCTS",
    GET_SELECTED_PRODUCTS="GET_SELECTED_PRODUCTS",
    GET_AVAILABLE_PRODUCTS="GET_AVAILABLE_PRODUCTS",
    EDIT_PRODUCT="EDIT_PRODUCT",
    SEARCH_PRODUCT="SEARCH_PRODUCT",
    NEW_PRODUCTS="NEW_PRODUCTS",

}
export enum ProductSommandeActions{
    ADD_PRODUCT="ADD_PRODUCT",
    DELETE_PRODUCT="DELETE_PRODUCT",
    UPDATE_PRODUCT="UPDATE_PRODUCT",
    SELECT_PRODUCT="SELECT_PRODUCT",
    EDIT_PRODUCT="EDIT_PRODUCT",
}
export interface ActionEvent<A,T>{
    type:A;
    payload?:T;
}